runtime: go
api_version: go1
nobuild_files: ^(go-netbsd|pkg)/

handlers:
- url: /go-pkgsrc/
  static_files: go-pkgsrc/index.html
  upload: go-pkgsrc/index.html
- url: /go-pkgsrc
  static_dir: go-pkgsrc
- url: /static
  static_dir: present/static
- url: /.*
  script: _go_app

